# Generated by Django 4.0.2 on 2022-10-20 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastForCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_dt', models.DateTimeField()),
                ('current_description', models.CharField(max_length=100)),
                ('current_icon', models.CharField(max_length=100)),
                ('current_rain', models.FloatField()),
                ('current_temp', models.IntegerField()),
                ('hourly_04_description', models.CharField(max_length=100)),
                ('hourly_08_description', models.CharField(max_length=100)),
                ('hourly_12_description', models.CharField(max_length=100)),
                ('hourly_16_description', models.CharField(max_length=100)),
                ('hourly_20_description', models.CharField(max_length=100)),
                ('hourly_24_description', models.CharField(max_length=100)),
                ('hourly_28_description', models.CharField(max_length=100)),
                ('hourly_32_description', models.CharField(max_length=100)),
                ('hourly_36_description', models.CharField(max_length=100)),
                ('hourly_40_description', models.CharField(max_length=100)),
                ('hourly_44_description', models.CharField(max_length=100)),
                ('hourly_48_description', models.CharField(max_length=100)),
                ('daily_1_description', models.CharField(max_length=100)),
                ('daily_2_description', models.CharField(max_length=100)),
                ('daily_3_description', models.CharField(max_length=100)),
                ('daily_4_description', models.CharField(max_length=100)),
                ('daily_5_description', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.city')),
            ],
        ),
    ]
